title: TUTORIA EN LINEA
email: tutoriaenLinea@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Tutorias en linea con todo lo que un profesional necesita para 
  su mundo laboral.
baseurl: "/myNewSite" # the subpath of your site, e.g. /blog
url: "https://juli027.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mandarinas_
github_username:  juli027

# Build settings
theme: minima
plugins:
  - jekyll-feed
